version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - 'mongoData:/data/db'
    ports:
      - 27017:27017

  app:
    image: myreact
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongoData: